//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.17929
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NntpClientLib {
    using System;
	using System.Resources;
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("binsync.Core.External.NntpClientLib.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to setup session after connection to NNTP server. ähnelt.
        /// </summary>
        internal static string ErrorMessage01 {
            get {
                return ResourceManager.GetString("ErrorMessage01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die GROUP command failed. ähnelt.
        /// </summary>
        internal static string ErrorMessage02 {
            get {
                return ResourceManager.GetString("ErrorMessage02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Incorrect direction command, it must be LAST or NEXT. ähnelt.
        /// </summary>
        internal static string ErrorMessage03 {
            get {
                return ResourceManager.GetString("ErrorMessage03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to move the selected article cursor in the current group. ähnelt.
        /// </summary>
        internal static string ErrorMessage04 {
            get {
                return ResourceManager.GetString("ErrorMessage04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Failed to get statistics for current group. ähnelt.
        /// </summary>
        internal static string ErrorMessage05 {
            get {
                return ResourceManager.GetString("ErrorMessage05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not post to group. ähnelt.
        /// </summary>
        internal static string ErrorMessage06 {
            get {
                return ResourceManager.GetString("ErrorMessage06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Article failed to post to group. ähnelt.
        /// </summary>
        internal static string ErrorMessage07 {
            get {
                return ResourceManager.GetString("ErrorMessage07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Slave command failed. ähnelt.
        /// </summary>
        internal static string ErrorMessage08 {
            get {
                return ResourceManager.GetString("ErrorMessage08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message Id must begin with &lt; and end with &gt;. ähnelt.
        /// </summary>
        internal static string ErrorMessage09 {
            get {
                return ResourceManager.GetString("ErrorMessage09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Message Id must begin with &lt; and end with &gt; and contain a message. ähnelt.
        /// </summary>
        internal static string ErrorMessage10 {
            get {
                return ResourceManager.GetString("ErrorMessage10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Client is not connected to server. ähnelt.
        /// </summary>
        internal static string ErrorMessage11 {
            get {
                return ResourceManager.GetString("ErrorMessage11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die NNTP command failed, unexpected response code. ähnelt.
        /// </summary>
        internal static string ErrorMessage12 {
            get {
                return ResourceManager.GetString("ErrorMessage12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Response input string should contain at least 3 fields, possibly 4. ähnelt.
        /// </summary>
        internal static string ErrorMessage13 {
            get {
                return ResourceManager.GetString("ErrorMessage13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Required password was not accepted. ähnelt.
        /// </summary>
        internal static string ErrorMessage30 {
            get {
                return ResourceManager.GetString("ErrorMessage30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unable to authenticate. ähnelt.
        /// </summary>
        internal static string ErrorMessage31 {
            get {
                return ResourceManager.GetString("ErrorMessage31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No previous response was received. ähnelt.
        /// </summary>
        internal static string ErrorMessage41 {
            get {
                return ResourceManager.GetString("ErrorMessage41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Response code is missing. ähnelt.
        /// </summary>
        internal static string ErrorMessage42 {
            get {
                return ResourceManager.GetString("ErrorMessage42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die The minimum size of the buffer must be positive. ähnelt.
        /// </summary>
        internal static string ErrorMessage43 {
            get {
                return ResourceManager.GetString("ErrorMessage43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Cannot read stream. ähnelt.
        /// </summary>
        internal static string ErrorMessage44 {
            get {
                return ResourceManager.GetString("ErrorMessage44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Can not read from underlying stream. ähnelt.
        /// </summary>
        internal static string ErrorMessage45 {
            get {
                return ResourceManager.GetString("ErrorMessage45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unrecognized date format requested, &apos;R&apos; is the only accepted format argument. ähnelt.
        /// </summary>
        internal static string ErrorMessage46 {
            get {
                return ResourceManager.GetString("ErrorMessage46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die String is not a valid date time. ähnelt.
        /// </summary>
        internal static string ErrorMessage47 {
            get {
                return ResourceManager.GetString("ErrorMessage47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Response input string should contain 2 or 3 fields separated by spaces. ähnelt.
        /// </summary>
        internal static string ErrorMessage48 {
            get {
                return ResourceManager.GetString("ErrorMessage48", resourceCulture);
            }
        }
    }
}
